export const randomName = () => {
    const gameCharacters = [
        "Solid Snake",
        "Big Boss",
        "Revolver Ocelot",
        "Liquid Snake",
        "Raiden Shogun",
        "Master Chief",
        "Lara Croft",
        "Nathan Drake",
        "Kratos Godkiller",
        "Duke Nukem",
        "Gordon Freeman",
        "Jill Valentine",
        "Chris Redfield",
        "Ada Wong",
        "Leon Kennedy",
        "Tommy Vercetti",
        "Carl Johnson",
        "Trevor Philips",
        "Michael De Santa",
        "Franklin Clinton",
        "Ezio Auditore",
        "Altaïr Ibn-La'Ahad",
        "Arthur Morgan",
        "John Marston",
        "Dutch van der Linde",
        "Max Payne",
        "Alan Wake",
        "Ellie Williams",
        "Joel Miller",
        "Marcus Fenix",
        "Dom Santiago",
        "Sam Fisher",
        "Isaac Clarke",
        "Isaac Briggs",
        "Commander Shepard",
        "Jack Cooper",
        "Booker DeWitt",
        "Elizabeth Comstock",
        "Corvo Attano",
        "Emily Kaldwin",
        "Geralt of Rivia",
        "Ciri Fiona Elen",
        "Yennefer Vengerberg",
        "Johnny Silverhand",
        "V Miles",
        "HK-47 Assassin",
        "Cal Kestis",
        "Sora Kingdom",
        "Roxas Nobody",
        "Cloud Strife"
    ]

    return gameCharacters[Math.floor(Math.random() * gameCharacters.length)]
}
