name: "Build and push image, deploy"

on:
  push:
    branches:
      - "feature/replace-deploy-vars-in-cicd"

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: asctod/game-library-ui:latest,asctod/game-library-ui:${{ github.sha }}

    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CLUSTER_CONFIG }}

    - name: Replace deployment variables
      run: |
        sed -i'' -e 's/_K8S_URL_/${{ secrets.K8S_URL }}/g' -e 's/_IMAGE_TAG_/${{ github.sha }}/g' -e 's/_ACME_EMAIL_/${{ secrets.ACME_EMAIL }}/g' deploy/*.yaml

    - name: Kubernetes Apply configs
      run: | 
        kubectl apply -f deploy/config.yaml
        kubectl apply -f deploy/deployment.yaml
        kubectl apply -f deploy/service.yaml
        kubectl apply -f deploy/ingress.yaml
